### ISSUE TITLE
bug in ARF._load_arf

### ISSUE THREAD

**Issue by eblur** [dhuppenkothen/clarsach#13]
_load_arf function relies on "ENERG_LO" and "ENERG_HI".  However, the "SPECRESP" field is not always in energy units.  

For HETG data:
I think that the specresp field is listed backwards (in angstrom) order.  I would recommend relying on "BIN_LO" and "BIN_HI" because it is more universal and will more likely reflect the order in which the SPECRESP field is listed.

OR we will need to account for units in the apply_arf function

**Comment by eblur** [comment]
Do the non-Chandra ARFs have BIN_LO and BIN_HI fields?

**Comment by eblur** [comment]
Okay, after a lot of staring, I have decided that my eyes were merely deceiving me.  Even though the Chandra ARF files indeed give energy and angstrom units, it appears that the SPECRESP column is sorted by energy.  The angstrom columns are in descending order (meaning that they match up with the order of the energy column.) We probably figured this out awhile ago, and I forgot.

**Comment by dhuppenkothen** [comment]
:)
